
package com.example.soapconsumer.marshall;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PostMessage", targetNamespace = "http://www.mahesh.com/spring/soap/api/inputRequest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostMessage {


    /**
     * 
     * @param soapRequest
     */
    @WebMethod(operationName = "Soap")
    @Oneway
    public void soap(
        @WebParam(name = "SoapRequest", targetNamespace = "http://www.mahesh.com/spring/soap/api/inputRequest", partName = "SoapRequest")
                SoapRequest soapRequest);

}
